#!/usr/bin/env node

const path = require('path')
const buble = require('rollup-plugin-buble')
const rollup = require('rollup')
const glob = require('glob')

const transform = input => rollup.rollup({
  input: path.resolve(input),
  external: ['tape'],
  plugins: [buble()]
})
  .then(bundle => bundle.generate({ format: 'iife' }))
  .then(({ code }) => code)
  .catch(err => { throw err })

const files = glob.sync(process.argv[2])
Promise.all(files.map(transform))
  // eslint-disable-next-line
  .then(codes => codes.forEach(c => eval(c)))
